[user]
username = "laughingsheep"
email = "hoster@thejodo.com"
discord = "Jodo#3210"

[records]
CNAME = "dc2833e0-5766-4a1a-92a6-265f9c0ae5d2.id.repl.co"
TXT = "replit-verify=dc2833e0-5766-4a1a-92a6-265f9c0ae5d2"